### ISSUE TITLE
LustyBufferExplorer/Grep throws error (VIM 7.3)

### ISSUE THREAD

**Issue by sickill** [sjbach/lusty#12]
Hi,

I'm using Vim 7.3 on ArchLinux and I'me getting following error when trying to invoke buffer explorer or buffer grep:

undefined method `full_name' for nil:NilClass                                                                                                                                      
(eval):362:in`block in compute_buffer_entries'  
(eval):361:in `each'                                                                                                                                                               
(eval):361:in`compute_buffer_entries'  
(eval):592:in `run'                                                                                                                                                                
(eval):1:in`block in <main>'  
(eval):212:in `profile'                                                                                                                                                            
(eval):1:in`<main>'

Probably sth with Vim 7.3, as I remember correctly it worked fine in 7.2.

And I also noticed that LustyJuggler doesn't find any open buffers, it always shows "No other buffers".

**Comment by sjbach** [comment]
Probably not many folks using Ruby 1.8 or these older versions of Vim.  Closing for now, but feel free to re-open.
